const P={yamashina:{name:"京都市山科区 北花山河原町",lat:34.988583,lon:135.800881},obama:{name:"福井県 小浜漁港",lat:35.502955,lon:135.735097},maizuru:{name:"京都府 舞鶴港",lat:35.47,lon:135.36},takahama:{name:"福井県 高浜町",lat:35.487522,lon:135.544846}};
const K={snap:"okaWx.snapshots.v1",verify:"okaWx.verifies.v1",place:"okaWx.lastPlace.v1"};let place={...P.yamashina},base=null,prev=null;
const $=x=>document.getElementById(x),f=v=>Number.isFinite(Number(v))?Number(v).toFixed(1):"--",pad=n=>String(n).padStart(2,"0");
const store=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||"")}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function wx(c){c=Number(c);if(c===0)return["☀️","快晴"];if([1,2].includes(c))return["🌤️","晴れ"];if(c===3)return["☁️","くもり"];if([45,48].includes(c))return["🌫️","霧"];if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(c))return["🌧️","雨"];if([71,73,75,77,85,86].includes(c))return["🌨️","雪"];if([95,96,97,99].includes(c))return["⛈️","雷雨"];return["🌥️","天気"]}
function comp(d){const a=["北","北北東","北東","東北東","東","東南東","南東","南南東","南","南南西","南西","西南西","西","西北西","北西","北北西"];return Number.isFinite(Number(d))?a[Math.round((Number(d)%360)/22.5)%16]:"--"}
function url(kind="best"){let b="https://api.open-meteo.com/v1/forecast";if(kind==="jma")b="https://api.open-meteo.com/v1/jma";if(kind==="ecmwf")b="https://api.open-meteo.com/v1/ecmwf";const u=new URL(b);u.searchParams.set("latitude",place.lat);u.searchParams.set("longitude",place.lon);u.searchParams.set("timezone","Asia/Tokyo");u.searchParams.set("forecast_days","3");u.searchParams.set("wind_speed_unit","ms");u.searchParams.set("precipitation_unit","mm");const common="temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_direction_10m";if(kind==="best"){u.searchParams.set("current",common+",wind_gusts_10m");u.searchParams.set("hourly",common+",wind_gusts_10m,precipitation_probability");u.searchParams.set("daily","weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max,wind_gusts_10m_max")}else u.searchParams.set("hourly","temperature_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m");return u}
async function get(u){const c=new AbortController(),t=setTimeout(()=>c.abort(),14000);try{const r=await fetch(u,{signal:c.signal,cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);return await r.json()}finally{clearTimeout(t)}}
function busy(on,msg="取得中"){ $("fetch").disabled=on;$("models").disabled=on;$("status").textContent=on?"● "+msg:(base?"● 取得済み":"● 未取得")}
function rows(d=base){if(!d?.hourly?.time)return[];return d.hourly.time.map((t,i)=>({time:t,temp:d.hourly.temperature_2m?.[i],hum:d.hourly.relative_humidity_2m?.[i],feel:d.hourly.apparent_temperature?.[i],rain:d.hourly.precipitation?.[i],pop:d.hourly.precipitation_probability?.[i],code:d.hourly.weather_code?.[i],wind:d.hourly.wind_speed_10m?.[i],dir:d.hourly.wind_direction_10m?.[i],gust:d.hourly.wind_gusts_10m?.[i]}))}
function nearest(a,d){let x=null,z=Infinity;for(const r of a){const q=Math.abs(new Date(r.time)-d);if(q<z){z=q;x=r}}return x}
function fmt(t){const d=new Date(t);return (d.getMonth()+1)+"/"+d.getDate()+" "+pad(d.getHours())+":00"}
function between(a,s,e){return a.filter(r=>{const t=new Date(r.time);return t>=s&&t<=e})}
function wet(r){return Number(r.rain)>=.1||Number(r.pop)>=50}
function windows(a){const o=[];let c=null;for(const r of a){if(wet(r)){if(!c)c={start:r.time,end:r.time,peak:Number(r.rain)||0,pop:Number(r.pop)||0};c.end=r.time;c.peak=Math.max(c.peak,Number(r.rain)||0);c.pop=Math.max(c.pop,Number(r.pop)||0)}else if(c){o.push(c);c=null}}if(c)o.push(c);return o}
function table(head,body){return '<div class="table"><table><thead><tr>'+head.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>"+body+"</tbody></table></div>"}
function hero(){const c=base.current,[i,t]=wx(c.weather_code);$("icon").textContent=i;$("temp").textContent=f(c.temperature_2m)+"°";$("cond").textContent=t;$("feel").textContent=f(c.apparent_temperature)+"°";$("hum").textContent=Math.round(c.relative_humidity_2m||0)+"%";$("wind").textContent=f(c.wind_speed_10m)+" / "+f(c.wind_gusts_10m);$("rainNow").textContent=f(c.precipitation)+" mm";$("updated").textContent=new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}
function headline(){const a=between(rows(),new Date(),new Date(Date.now()+864e5)),w=windows(a),g=Math.max(0,...a.map(x=>Number(x.gust)||0)),v=Math.max(0,...a.map(x=>Number(x.wind)||0)),th=a.find(x=>[95,96,97,99].includes(Number(x.code)));const s=[w.length?"雨は "+fmt(w[0].start)+" ごろから "+fmt(w[0].end)+" ごろまでが第一候補":"24時間以内はまとまった雨の信号は弱め",g>=10?"突風 最大 "+f(g)+"m/s に注意":v>=6?"風 最大 "+f(v)+"m/s":"風は強風域ではない"];if(th)s.push("雷雨コード "+fmt(th.time)+" 前後");$("headline").textContent=s.join("。")+"。"}
function today(){const a=rows(),up=a.filter(x=>new Date(x.time)>=new Date(Date.now()-18e5)).slice(0,12);$("timeline").className="timeline";$("timeline").innerHTML=up.map(r=>'<div class="hour"><small>'+pad(new Date(r.time).getHours())+':00</small><div style="font-size:22px">'+wx(r.code)[0]+'</div><b>'+f(r.temp)+'°</b><small>☔ '+(Number.isFinite(Number(r.pop))?Math.round(r.pop)+"%":f(r.rain)+"mm")+'</small><small>風 '+f(r.wind)+' / '+f(r.gust)+'</small></div>').join("");const n=new Date(),s=new Date(n.getFullYear(),n.getMonth(),n.getDate(),6),e=new Date(s.getTime()+864e5),win=between(a,s,e);$("dayTable").innerHTML=table(["時刻","天気","気温","降水","確率","風","突風"],win.map(r=>"<tr><td>"+fmt(r.time)+"</td><td>"+wx(r.code)[0]+"</td><td>"+f(r.temp)+"°</td><td>"+f(r.rain)+"mm</td><td>"+(Number.isFinite(Number(r.pop))?Math.round(r.pop)+"%":"--")+"</td><td>"+comp(r.dir)+" "+f(r.wind)+"</td><td>"+f(r.gust)+"</td></tr>").join(""))}
function rainWind(){const a=between(rows(),new Date(),new Date(Date.now()+48*36e5)),w=windows(a);$("rainEvents").innerHTML=w.length?w.map((x,i)=>'<div class="event"><b>'+(i+1)+'回目 '+fmt(x.start)+' → '+fmt(x.end)+'</b><p>最大降水 '+f(x.peak)+'mm/h・確率 '+Math.round(x.pop)+'%</p></div>').join(""):'<div class="event"><b>48時間以内に明瞭な雨時間帯なし</b></div>';const top=[...a].sort((x,y)=>(Number(y.gust)||0)-(Number(x.gust)||0)).slice(0,5);$("windEvents").innerHTML=top.map(r=>'<div class="event"><b>'+fmt(r.time)+' '+comp(r.dir)+' '+f(r.wind)+'m/s　突風 '+f(r.gust)+'m/s</b><p>'+(Number(r.gust)>=10?"風の山・注意":"比較的穏やか")+'</p></div>').join("")}
function tomorrow(){const a=rows(),n=new Date(),d=new Date(n.getFullYear(),n.getMonth(),n.getDate()+1),hs=[6,9,12,15,18,21],body=hs.map(h=>{const x=nearest(a,new Date(n.getFullYear(),n.getMonth(),n.getDate(),h)),y=nearest(a,new Date(d.getFullYear(),d.getMonth(),d.getDate(),h)),q=Number(y.temp)-Number(x.temp);return "<tr><td>"+h+":00</td><td>"+f(x.temp)+"°</td><td>"+f(y.temp)+"°</td><td>"+(q>=0?"+":"")+f(q)+"°</td><td>"+f(x.rain)+"→"+f(y.rain)+"mm</td><td>"+f(x.wind)+"→"+f(y.wind)+"m/s</td></tr>"}).join("");$("tomorrowTable").innerHTML=table(["時刻","今日","明日","差","降水","風"],body)}
function life(){const d=base.daily,max=Number(d.temperature_2m_max?.[0]),min=Number(d.temperature_2m_min?.[1]??d.temperature_2m_min?.[0]);$("maxT").textContent=f(max)+"°";$("minT").textContent=f(min)+"°";$("tropical").textContent=min>=25?"熱帯夜":"該当せず";const hum=Math.max(0,...rows().slice(0,24).map(r=>Number(r.hum)||0));let s=max>=30?"冷房26℃前後・自動運転を基準。留守番時は切タイマーなし寄り。":max>=28||hum>=75?"冷房26〜27℃前後または除湿。湿度の上がりすぎに注意。":max>=25?"室温を見て26〜27℃前後または除湿。":"外気は低め。室温・湿度を見て必要時だけ空調。";if(min>=25)s+=" 夜も朝方まで弱冷房/除湿寄り。";$("aircon").textContent=s;$("airconShort").textContent=max>=28?"冷房寄り":"様子見"}
function snap(){return{at:new Date().toISOString(),place:{name:place.name,lat:place.lat,lon:place.lon},hourly:rows().slice(0,72).map(r=>({time:r.time,temp:r.temp,wind:r.wind,rain:r.rain,gust:r.gust,pop:r.pop}))}}
function same(a,b){return a&&b&&Math.abs(Number(a.lat)-Number(b.lat))<.002&&Math.abs(Number(a.lon)-Number(b.lon))<.002}
function verify(){const all=store(K.snap).filter(s=>same(s.place,place)),now=new Date(),key=now.getFullYear()+"-"+pad(now.getMonth()+1)+"-"+pad(now.getDate())+"T"+pad(now.getHours())+":00",cur=base.current;let v=store(K.verify),seen=new Set(v.map(x=>x.at+"|"+x.target));for(const s of all.slice(-8)){const p=s.hourly?.find(x=>x.time===key),id=s.at+"|"+key;if(p&&!seen.has(id))v.push({at:s.at,target:key,place:s.place.name,t:Math.abs(Number(p.temp)-Number(cur.temperature_2m)),w:Math.abs(Number(p.wind)-Number(cur.wind_speed_10m)),r:(Number(p.rain)>=.1)===(Number(cur.precipitation)>=.1)})}save(K.verify,v.slice(-120))}
function accuracy(cur){const p=prev;if(p){const a=between(p.hourly.map(x=>({...x})),new Date(),new Date(Date.now()+864e5)),b=between(cur.hourly.map(x=>({...x})),new Date(),new Date(Date.now()+864e5)),m=new Map(b.map(x=>[x.time,x])),q=a.map(x=>[x,m.get(x.time)]).filter(x=>x[1]);if(q.length){const td=Math.max(...q.map(x=>Number(x[1].temp)))-Math.max(...q.map(x=>Number(x[0].temp))),gd=Math.max(...q.map(x=>Number(x[1].gust)||0))-Math.max(...q.map(x=>Number(x[0].gust)||0));$("change").innerHTML='<div class="event"><b>24時間最高気温 '+(td>=0?"+":"")+f(td)+'℃ / 最大突風 '+(gd>=0?"+":"")+f(gd)+'m/s の変化</b></div>'}}const v=store(K.verify).filter(x=>!x.place||x.place===place.name);$("nVerify").textContent=v.length;if(v.length){const mean=k=>v.reduce((s,x)=>s+Number(x[k]||0),0)/v.length;$("tMae").textContent=f(mean("t"))+"℃";$("wMae").textContent=f(mean("w"))+"m/s";$("rHit").textContent=Math.round(v.filter(x=>x.r).length/v.length*100)+"%"}}
function persist(){let a=store(K.snap);prev=[...a].reverse().find(x=>same(x.place,place))||null;const c=snap();a.push(c);save(K.snap,a.slice(-30));accuracy(c)}
function render(){hero();headline();today();rainWind();tomorrow();life();persist()}
async function load(){busy(true,"天気取得中");try{base=await get(url());verify();render()}catch(e){console.error(e);alert("天気データを取得できませんでした")}finally{busy(false)}}
function norm(d){return d.hourly.time.map((t,i)=>({time:t,temp:d.hourly.temperature_2m?.[i],rain:d.hourly.precipitation?.[i],wind:d.hourly.wind_speed_10m?.[i]}))}
async function compare(){busy(true,"3モデル取得中");try{if(!base){base=await get(url());verify();render()}const z=await Promise.all([get(url("jma")),get(url("ecmwf"))]),sets=[norm(base),norm(z[0]),norm(z[1])],now=new Date(),hs=[0,3,6,9,12,18,24],out=[],score=[];for(const h of hs){const d=new Date(now.getTime()+h*36e5),r=sets.map(s=>nearest(s,d));if(r.some(x=>!x))continue;const ts=r.map(x=>Number(x.temp)),ws=r.map(x=>Number(x.wind)),rs=r.map(x=>Number(x.rain));score.push(Math.max(...ts)-Math.min(...ts)+.45*(Math.max(...ws)-Math.min(...ws))+.25*(Math.max(...rs)-Math.min(...rs)));out.push("<tr><td>"+fmt(r[0].time)+"</td>"+r.map(x=>"<td>"+f(x.temp)+"℃ / ☔"+f(x.rain)+" / 風"+f(x.wind)+"</td>").join("")+"</tr>")}const avg=score.reduce((s,x)=>s+x,0)/(score.length||1),c=Math.max(20,Math.min(98,Math.round(96-avg*12)));$("confidence").textContent="一致度 "+c+"%";$("confidence").className="badge "+(c>=80?"good":c>=60?"warn":"bad");$("modelTable").innerHTML=table(["時刻","Best Match","JMA系","ECMWF"],out.join(""));document.querySelector('[data-tab="model"]').click()}catch(e){console.error(e);alert("モデル比較に失敗しました")}finally{busy(false)}}
function setPlace(k){if(k==="current"){locate();return}place={...P[k]};$("placeName").textContent=place.name;save(K.place,k);base=null;$("status").textContent="● 未取得";$("temp").textContent="--°";$("cond").textContent="ボタンを押すまで天気通信しません"}
function locate(){if(!navigator.geolocation)return alert("現在地取得に対応していません");$("locate").textContent="取得中…";navigator.geolocation.getCurrentPosition(p=>{place={name:"現在地",lat:p.coords.latitude,lon:p.coords.longitude};$("placeName").textContent="現在地";$("place").value="current";base=null;$("status").textContent="● 未取得";$("locate").textContent="📍 現在地"},()=>{$("locate").textContent="📍 現在地";alert("現在地を取得できませんでした")},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("on"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("on"));b.classList.add("on");$(b.dataset.tab).classList.add("on")});
$("fetch").onclick=load;$("models").onclick=compare;$("locate").onclick=locate;$("home").onclick=()=>{$("place").value="yamashina";setPlace("yamashina")};$("place").onchange=e=>setPlace(e.target.value);$("clear").onclick=()=>{if(confirm("学習履歴を消去しますか？")){localStorage.removeItem(K.snap);localStorage.removeItem(K.verify);location.reload()}};
addEventListener("offline",()=>{$("status").textContent="● オフライン"});const last=localStorage.getItem(K.place);if(last&&P[last]){$("place").value=last;setPlace(last)}if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));