const P={yamashina:{name:"京都市山科区 北花山河原町",lat:34.988583,lon:135.800881},obama:{name:"福井県 小浜漁港",lat:35.502955,lon:135.735097},maizuru:{name:"京都府 舞鶴港",lat:35.47,lon:135.36},takahama:{name:"福井県 高浜町",lat:35.487522,lon:135.544846}};
const K={state:"okaWx.locations.v2",last:"okaWx.lastPlace.v2",oldSnap:"okaWx.snapshots.v1",oldVerify:"okaWx.verifies.v1"};let place={...P.yamashina},base=null,prev=null;
const $=x=>document.getElementById(x),f=v=>Number.isFinite(Number(v))?Number(v).toFixed(1):"--",pad=n=>String(n).padStart(2,"0");
const loadJSON=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k)||"");return x??d}catch{return d}},saveJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const keyOf=p=>Number(p.lat).toFixed(3)+","+Number(p.lon).toFixed(3);
function state(){const s=loadJSON(K.state,null);return s&&s.version===2?s:{version:2,locations:{},favorites:[]}}
function putState(s){saveJSON(K.state,s);updateStorage(s)}
function ensureLoc(s,p=place){const k=keyOf(p);if(!s.locations[k])s.locations[k]={name:p.name,lat:p.lat,lon:p.lon,lastUsed:Date.now(),snapshots:[],verifies:[]};const z=s.locations[k];z.name=p.name;z.lat=p.lat;z.lon=p.lon;z.lastUsed=Date.now();return z}
function trimState(s){const fav=new Set(s.favorites||[]),keys=Object.keys(s.locations);if(keys.length<=8)return;keys.sort((a,b)=>(s.locations[a].lastUsed||0)-(s.locations[b].lastUsed||0));for(const k of keys){if(Object.keys(s.locations).length<=8)break;if(k!==keyOf(place)&&!fav.has(k))delete s.locations[k]}}
function migrate(){if(localStorage.getItem(K.state))return;const s=state(),sn=loadJSON(K.oldSnap,[]),vv=loadJSON(K.oldVerify,[]),nameMap={};for(const x of sn){if(!x?.place)continue;const k=keyOf(x.place),z=ensureLoc(s,x.place);z.snapshots.push(x);nameMap[x.place.name]=k}for(const v of vv){const k=nameMap[v.place];if(k&&s.locations[k])s.locations[k].verifies.push(v)}for(const z of Object.values(s.locations)){z.snapshots=z.snapshots.slice(-16);z.verifies=z.verifies.slice(-100)}trimState(s);putState(s)}
function wx(c){c=Number(c);if(c===0)return["☀️","快晴"];if([1,2].includes(c))return["🌤️","晴れ"];if(c===3)return["☁️","くもり"];if([45,48].includes(c))return["🌫️","霧"];if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(c))return["🌧️","雨"];if([71,73,75,77,85,86].includes(c))return["🌨️","雪"];if([95,96,97,99].includes(c))return["⛈️","雷雨"];return["🌥️","天気"]}
function comp(d){const a=["北","北北東","北東","東北東","東","東南東","南東","南南東","南","南南西","南西","西南西","西","西北西","北西","北北西"];return Number.isFinite(Number(d))?a[Math.round((Number(d)%360)/22.5)%16]:"--"}
function url(kind="best"){let b="https://api.open-meteo.com/v1/forecast";if(kind==="jma")b="https://api.open-meteo.com/v1/jma";if(kind==="ecmwf")b="https://api.open-meteo.com/v1/ecmwf";const u=new URL(b);u.searchParams.set("latitude",place.lat);u.searchParams.set("longitude",place.lon);u.searchParams.set("timezone","Asia/Tokyo");u.searchParams.set("forecast_days","7");u.searchParams.set("wind_speed_unit","ms");u.searchParams.set("precipitation_unit","mm");const common="temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_direction_10m";if(kind==="best"){u.searchParams.set("current",common+",wind_gusts_10m");u.searchParams.set("hourly",common+",wind_gusts_10m,precipitation_probability");u.searchParams.set("daily","weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max,wind_gusts_10m_max")}else u.searchParams.set("hourly","temperature_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m");return u}
function geocodeUrl(q){const u=new URL("https://geocoding-api.open-meteo.com/v1/search");u.searchParams.set("name",q);u.searchParams.set("count","6");u.searchParams.set("language","ja");u.searchParams.set("format","json");u.searchParams.set("countryCode","JP");return u}
async function get(u){const c=new AbortController(),t=setTimeout(()=>c.abort(),14000);try{const r=await fetch(u,{signal:c.signal,cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);return await r.json()}finally{clearTimeout(t)}}
function busy(on,msg="取得中"){$("fetch").disabled=on;$("models").disabled=on;$("searchBtn").disabled=on;$("status").textContent=on?"● "+msg:(base?"● 取得済み":"● 未取得")}
function rows(d=base){if(!d?.hourly?.time)return[];return d.hourly.time.map((t,i)=>({time:t,temp:d.hourly.temperature_2m?.[i],hum:d.hourly.relative_humidity_2m?.[i],feel:d.hourly.apparent_temperature?.[i],rain:d.hourly.precipitation?.[i],pop:d.hourly.precipitation_probability?.[i],code:d.hourly.weather_code?.[i],wind:d.hourly.wind_speed_10m?.[i],dir:d.hourly.wind_direction_10m?.[i],gust:d.hourly.wind_gusts_10m?.[i]}))}
function nearest(a,d){let x=null,z=Infinity;for(const r of a){const q=Math.abs(new Date(r.time)-d);if(q<z){z=q;x=r}}return x}
function fmt(t){const d=new Date(t);return(d.getMonth()+1)+"/"+d.getDate()+" "+pad(d.getHours())+":00"}
function between(a,s,e){return a.filter(r=>{const t=new Date(r.time);return t>=s&&t<=e})}
function wet(r){return Number(r.rain)>=.1||Number(r.pop)>=50}
function windows(a){const o=[];let c=null;for(const r of a){if(wet(r)){if(!c)c={start:r.time,end:r.time,peak:Number(r.rain)||0,pop:Number(r.pop)||0};c.end=r.time;c.peak=Math.max(c.peak,Number(r.rain)||0);c.pop=Math.max(c.pop,Number(r.pop)||0)}else if(c){o.push(c);c=null}}if(c)o.push(c);return o}
function table(head,body){return'<div class="table"><table><thead><tr>'+head.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>"+body+"</tbody></table></div>"}
function hero(){const c=base.current,[i,t]=wx(c.weather_code);$("icon").textContent=i;$("temp").textContent=f(c.temperature_2m)+"°";$("cond").textContent=t;$("feel").textContent=f(c.apparent_temperature)+"°";$("hum").textContent=Math.round(c.relative_humidity_2m||0)+"%";$("wind").textContent=f(c.wind_speed_10m)+" / "+f(c.wind_gusts_10m);$("rainNow").textContent=f(c.precipitation)+" mm";$("updated").textContent=new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}
function headline(){const a=between(rows(),new Date(),new Date(Date.now()+864e5)),w=windows(a),g=Math.max(0,...a.map(x=>Number(x.gust)||0)),v=Math.max(0,...a.map(x=>Number(x.wind)||0)),th=a.find(x=>[95,96,97,99].includes(Number(x.code)));const s=[w.length?"雨は "+fmt(w[0].start)+" ごろから "+fmt(w[0].end)+" ごろまでが第一候補":"24時間以内はまとまった雨の信号は弱め",g>=10?"突風 最大 "+f(g)+"m/s に注意":v>=6?"風 最大 "+f(v)+"m/s":"風は強風域ではない"];if(th)s.push("雷雨コード "+fmt(th.time)+" 前後");$("headline").textContent=s.join("。")+"。"}
function today(){const a=rows(),up=a.filter(x=>new Date(x.time)>=new Date(Date.now()-18e5)).slice(0,12);$("timeline").className="timeline";$("timeline").innerHTML=up.map(r=>'<div class="hour"><small>'+pad(new Date(r.time).getHours())+':00</small><div style="font-size:22px">'+wx(r.code)[0]+'</div><b>'+f(r.temp)+'°</b><small>☔ '+(Number.isFinite(Number(r.pop))?Math.round(r.pop)+"%":f(r.rain)+"mm")+'</small><small>風 '+f(r.wind)+' / '+f(r.gust)+'</small></div>').join("");const n=new Date(),s=new Date(n.getFullYear(),n.getMonth(),n.getDate(),6),e=new Date(s.getTime()+864e5),win=between(a,s,e);$("dayTable").innerHTML=table(["時刻","天気","気温","降水","確率","風","突風"],win.map(r=>"<tr><td>"+fmt(r.time)+"</td><td>"+wx(r.code)[0]+"</td><td>"+f(r.temp)+"°</td><td>"+f(r.rain)+"mm</td><td>"+(Number.isFinite(Number(r.pop))?Math.round(r.pop)+"%":"--")+"</td><td>"+comp(r.dir)+" "+f(r.wind)+"</td><td>"+f(r.gust)+"</td></tr>").join(""))}
function weekly(){const d=base?.daily;if(!d?.time?.length)return;const wd=["日","月","火","水","木","金","土"],n=Math.min(7,d.time.length),cards=[],trs=[];for(let i=0;i<n;i++){const dt=new Date(d.time[i]+"T12:00:00"),label=i===0?"今日":i===1?"明日":wd[dt.getDay()]+"曜",date=(dt.getMonth()+1)+"/"+dt.getDate(),code=d.weather_code?.[i],hi=d.temperature_2m_max?.[i],lo=d.temperature_2m_min?.[i],rain=d.precipitation_sum?.[i],wind=d.wind_speed_10m_max?.[i],gust=d.wind_gusts_10m_max?.[i];cards.push('<div class="weekcard"><div class="day">'+label+'</div><div class="date">'+date+'</div><div class="wx">'+wx(code)[0]+'</div><div class="hi">'+f(hi)+'°</div><div class="lo">'+f(lo)+'°</div><div class="rain">☔ '+f(rain)+'mm</div><div class="wind">風 '+f(wind)+' / '+f(gust)+'</div></div>');trs.push("<tr><td>"+date+" ("+wd[dt.getDay()]+")</td><td>"+wx(code)[0]+" "+wx(code)[1]+"</td><td>"+f(hi)+"°</td><td>"+f(lo)+"°</td><td>"+f(rain)+"mm</td><td>"+f(wind)+"m/s</td><td>"+f(gust)+"m/s</td></tr>")} $("weekCards").className="weekcards";$("weekCards").innerHTML=cards.join("");$("weekTable").innerHTML=table(["日付","天気","最高","最低","降水","最大風","最大突風"],trs.join(""))}
function rainWind(){const a=between(rows(),new Date(),new Date(Date.now()+48*36e5)),w=windows(a);$("rainEvents").innerHTML=w.length?w.map((x,i)=>'<div class="event"><b>'+(i+1)+'回目 '+fmt(x.start)+' → '+fmt(x.end)+'</b><p>最大降水 '+f(x.peak)+'mm/h・確率 '+Math.round(x.pop)+'%</p></div>').join(""):'<div class="event"><b>48時間以内に明瞭な雨時間帯なし</b></div>';const top=[...a].sort((x,y)=>(Number(y.gust)||0)-(Number(x.gust)||0)).slice(0,5);$("windEvents").innerHTML=top.map(r=>'<div class="event"><b>'+fmt(r.time)+' '+comp(r.dir)+' '+f(r.wind)+'m/s　突風 '+f(r.gust)+'m/s</b><p>'+(Number(r.gust)>=10?"風の山・注意":"比較的穏やか")+'</p></div>').join("")}
function tomorrow(){const a=rows(),n=new Date(),d=new Date(n.getFullYear(),n.getMonth(),n.getDate()+1),hs=[6,9,12,15,18,21],body=hs.map(h=>{const x=nearest(a,new Date(n.getFullYear(),n.getMonth(),n.getDate(),h)),y=nearest(a,new Date(d.getFullYear(),d.getMonth(),d.getDate(),h)),q=Number(y.temp)-Number(x.temp);return"<tr><td>"+h+":00</td><td>"+f(x.temp)+"°</td><td>"+f(y.temp)+"°</td><td>"+(q>=0?"+":"")+f(q)+"°</td><td>"+f(x.rain)+"→"+f(y.rain)+"mm</td><td>"+f(x.wind)+"→"+f(y.wind)+"m/s</td></tr>"}).join("");$("tomorrowTable").innerHTML=table(["時刻","今日","明日","差","降水","風"],body)}
function life(){const d=base.daily,max=Number(d.temperature_2m_max?.[0]),min=Number(d.temperature_2m_min?.[1]??d.temperature_2m_min?.[0]);$("maxT").textContent=f(max)+"°";$("minT").textContent=f(min)+"°";$("tropical").textContent=min>=25?"熱帯夜":"該当せず";const hum=Math.max(0,...rows().slice(0,24).map(r=>Number(r.hum)||0));let s=max>=30?"冷房26℃前後・自動運転を基準。留守番時は切タイマーなし寄り。":max>=28||hum>=75?"冷房26〜27℃前後または除湿。湿度の上がりすぎに注意。":max>=25?"室温を見て26〜27℃前後または除湿。":"外気は低め。室温・湿度を見て必要時だけ空調。";if(min>=25)s+=" 夜も朝方まで弱冷房/除湿寄り。";$("aircon").textContent=s;$("airconShort").textContent=max>=28?"冷房寄り":"様子見"}
function snapshot(){return{at:new Date().toISOString(),place:{name:place.name,lat:place.lat,lon:place.lon},hourly:rows().slice(0,48).map(r=>({time:r.time,temp:r.temp,wind:r.wind,rain:r.rain,gust:r.gust,pop:r.pop}))}}
function verifyCurrent(s,z){const now=new Date(),key=now.getFullYear()+"-"+pad(now.getMonth()+1)+"-"+pad(now.getDate())+"T"+pad(now.getHours())+":00",cur=base.current,seen=new Set(z.verifies.map(x=>x.at+"|"+x.target));for(const p0 of z.snapshots.slice(-8)){const p=p0.hourly?.find(x=>x.time===key),id=p0.at+"|"+key;if(p&&!seen.has(id))z.verifies.push({at:p0.at,target:key,t:Math.abs(Number(p.temp)-Number(cur.temperature_2m)),w:Math.abs(Number(p.wind)-Number(cur.wind_speed_10m)),r:(Number(p.rain)>=.1)===(Number(cur.precipitation)>=.1)})}z.verifies=z.verifies.slice(-100);putState(s)}
function updateAccuracy(z,cur){if(prev){const a=between(prev.hourly||[],new Date(),new Date(Date.now()+864e5)),b=between(cur.hourly||[],new Date(),new Date(Date.now()+864e5)),m=new Map(b.map(x=>[x.time,x])),q=a.map(x=>[x,m.get(x.time)]).filter(x=>x[1]);if(q.length){const td=Math.max(...q.map(x=>Number(x[1].temp)))-Math.max(...q.map(x=>Number(x[0].temp))),gd=Math.max(...q.map(x=>Number(x[1].gust)||0))-Math.max(...q.map(x=>Number(x[0].gust)||0));$("change").innerHTML='<div class="event"><b>24時間最高気温 '+(td>=0?"+":"")+f(td)+'℃ / 最大突風 '+(gd>=0?"+":"")+f(gd)+'m/s の変化</b></div>'}}const v=z.verifies||[];$("nVerify").textContent=v.length;if(v.length){const mean=k=>v.reduce((s,x)=>s+Number(x[k]||0),0)/v.length;$("tMae").textContent=f(mean("t"))+"℃";$("wMae").textContent=f(mean("w"))+"m/s";$("rHit").textContent=Math.round(v.filter(x=>x.r).length/v.length*100)+"%"}else{$("tMae").textContent="--";$("wMae").textContent="--";$("rHit").textContent="--"}const n=z.snapshots?.length||0;$("learnBadge").textContent="履歴 "+n;$("historyStage").textContent=n>=8?"蓄積中":n>=2?"学習準備":"初期";$("historyStage").className="badge "+(n>=8?"good":n>=2?"warn":"")}
function persist(){const s=state(),z=ensureLoc(s);prev=z.snapshots.at(-1)||null;const c=snapshot();z.snapshots.push(c);z.snapshots=z.snapshots.slice(-16);verifyCurrent(s,z);updateAccuracy(z,c);trimState(s);putState(s);renderFavorites()}
function updateStorage(s=state()){if(!$("storage"))return;const bytes=new Blob([JSON.stringify(s)]).size;$("storage").textContent="端末保存量 約 "+(bytes<1024?bytes+"B":bytes<1048576?(bytes/1024).toFixed(0)+"KB":(bytes/1048576).toFixed(2)+"MB")+" / 最大8地点・各16予報履歴"}
function renderHistoryStatus(){const s=state(),z=s.locations[keyOf(place)]||{snapshots:[],verifies:[]};const n=z.snapshots.length;$("learnBadge").textContent="履歴 "+n;$("historyStage").textContent=n>=8?"蓄積中":n>=2?"学習準備":"初期";$("nVerify").textContent=z.verifies.length;updateStorage(s)}
function render(){hero();headline();today();weekly();rainWind();tomorrow();life();persist()}
async function load(){busy(true,"天気取得中");try{base=await get(url());render()}catch(e){console.error(e);alert("天気データを取得できませんでした")}finally{busy(false)}}
function norm(d){return d.hourly.time.map((t,i)=>({time:t,temp:d.hourly.temperature_2m?.[i],rain:d.hourly.precipitation?.[i],wind:d.hourly.wind_speed_10m?.[i]}))}
async function compare(){busy(true,"3モデル取得中");try{if(!base){base=await get(url());render()}const z=await Promise.all([get(url("jma")),get(url("ecmwf"))]),sets=[norm(base),norm(z[0]),norm(z[1])],now=new Date(),hs=[0,3,6,9,12,18,24],out=[],score=[];for(const h of hs){const d=new Date(now.getTime()+h*36e5),r=sets.map(s=>nearest(s,d));if(r.some(x=>!x))continue;const ts=r.map(x=>Number(x.temp)),ws=r.map(x=>Number(x.wind)),rs=r.map(x=>Number(x.rain));score.push(Math.max(...ts)-Math.min(...ts)+.45*(Math.max(...ws)-Math.min(...ws))+.25*(Math.max(...rs)-Math.min(...rs)));out.push("<tr><td>"+fmt(r[0].time)+"</td>"+r.map(x=>"<td>"+f(x.temp)+"℃ / ☔"+f(x.rain)+" / 風"+f(x.wind)+"</td>").join("")+"</tr>")}const avg=score.reduce((s,x)=>s+x,0)/(score.length||1),c=Math.max(20,Math.min(98,Math.round(96-avg*12)));$("confidence").textContent="一致度 "+c+"%";$("confidence").className="badge "+(c>=80?"good":c>=60?"warn":"bad");$("modelTable").innerHTML=table(["時刻","Best Match","JMA系","ECMWF"],out.join(""));document.querySelector('[data-tab="model"]').click()}catch(e){console.error(e);alert("モデル比較に失敗しました")}finally{busy(false)}}
function activate(p,saveLast=true){place={name:p.name,lat:Number(p.lat),lon:Number(p.lon)};$("placeName").textContent=place.name;base=null;prev=null;$("status").textContent="● 未取得";$("temp").textContent="--°";$("cond").textContent="ボタンを押すまで天気通信しません";$("updated").textContent="未取得";if(saveLast)saveJSON(K.last,place);renderFavorites();renderHistoryStatus()}
function setPreset(k){if(k==="current"){locate();return}activate(P[k])}
function locate(){if(!navigator.geolocation)return alert("現在地取得に対応していません");$("locate").textContent="取得中…";navigator.geolocation.getCurrentPosition(p=>{activate({name:"現在地",lat:p.coords.latitude,lon:p.coords.longitude});$("place").value="current";$("locate").textContent="📍 現在地"},()=>{$("locate").textContent="📍 現在地";alert("現在地を取得できませんでした")},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function labelResult(r){return[r.name,r.admin3,r.admin2,r.admin1].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).join("・")}
async function searchPlace(){const q=$("searchInput").value.trim();if(q.length<2)return alert("2文字以上で検索してください");busy(true,"地点検索中");try{const d=await get(geocodeUrl(q)),rs=(d.results||[]).filter(x=>x.country_code==="JP");if(!rs.length){$("searchResults").innerHTML='<div class="results"><div class="empty">見つかりませんでした</div></div>';return}$("searchResults").innerHTML='<div class="results">'+rs.map((r,i)=>'<button class="result" data-result="'+i+'">'+r.name+'<small>'+[r.admin1,r.admin2,r.admin3].filter(Boolean).join(" / ")+'</small></button>').join("")+'</div>';$("searchResults").querySelectorAll("[data-result]").forEach(b=>b.onclick=()=>{const r=rs[Number(b.dataset.result)];activate({name:labelResult(r),lat:r.latitude,lon:r.longitude});$("searchResults").innerHTML="";$("searchInput").value=""})}catch(e){console.error(e);alert("地点検索に失敗しました")}finally{busy(false)}}
function renderFavorites(){const s=state(),k=keyOf(place),box=$("favorites"),fav=s.favorites||[];if(!fav.length)box.innerHTML='<span class="muted">まだありません</span>';else box.innerHTML=fav.filter(x=>s.locations[x]).map(x=>'<button class="favchip '+(x===k?"active":"")+'" data-fav="'+x+'">'+s.locations[x].name+'</button>').join("");box.querySelectorAll?.("[data-fav]").forEach(b=>b.onclick=()=>{const z=s.locations[b.dataset.fav];activate({name:z.name,lat:z.lat,lon:z.lon})});$("favorite").textContent=fav.includes(k)?"★ 登録済み":"☆ 追加"}
function toggleFavorite(){const s=state(),k=keyOf(place);ensureLoc(s);s.favorites=s.favorites||[];if(s.favorites.includes(k))s.favorites=s.favorites.filter(x=>x!==k);else{if(s.favorites.length>=8)return alert("お気に入りは最大8地点です");s.favorites.push(k)}trimState(s);putState(s);renderFavorites()}
function clearPlace(){if(!confirm("この地点の予報履歴だけ消去しますか？"))return;const s=state(),k=keyOf(place),z=s.locations[k];if(z){z.snapshots=[];z.verifies=[];putState(s)}$("change").textContent="同じ地点を2回以上取得すると変化を表示";$("tMae").textContent="--";$("wMae").textContent="--";$("rHit").textContent="--";renderHistoryStatus()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("on"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("on"));b.classList.add("on");$(b.dataset.tab).classList.add("on")});
$("fetch").onclick=load;$("models").onclick=compare;$("locate").onclick=locate;$("home").onclick=()=>{$("place").value="yamashina";setPreset("yamashina")};$("place").onchange=e=>setPreset(e.target.value);$("searchBtn").onclick=searchPlace;$("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter")searchPlace()});$("favorite").onclick=toggleFavorite;$("clearPlace").onclick=clearPlace;
addEventListener("offline",()=>{$("status").textContent="● オフライン"});migrate();const last=loadJSON(K.last,null);if(last?.lat&&last?.lon)activate(last,false);else activate(P.yamashina,false);if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));